// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lines.proto

package external_models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExternalLine struct {
	Objectid             string   `protobuf:"bytes,1,opt,name=objectid,proto3" json:"objectid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalLine) Reset()         { *m = ExternalLine{} }
func (m *ExternalLine) String() string { return proto.CompactTextString(m) }
func (*ExternalLine) ProtoMessage()    {}
func (*ExternalLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbecfaf73b19427e, []int{0}
}

func (m *ExternalLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalLine.Unmarshal(m, b)
}
func (m *ExternalLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalLine.Marshal(b, m, deterministic)
}
func (m *ExternalLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalLine.Merge(m, src)
}
func (m *ExternalLine) XXX_Size() int {
	return xxx_messageInfo_ExternalLine.Size(m)
}
func (m *ExternalLine) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalLine.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalLine proto.InternalMessageInfo

func (m *ExternalLine) GetObjectid() string {
	if m != nil {
		return m.Objectid
	}
	return ""
}

func (m *ExternalLine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ExternalLine)(nil), "external_models.ExternalLine")
}

func init() { proto.RegisterFile("lines.proto", fileDescriptor_cbecfaf73b19427e) }

var fileDescriptor_cbecfaf73b19427e = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0xcc, 0x4b,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4f, 0xad, 0x28, 0x49, 0x2d, 0xca, 0x4b,
	0xcc, 0x89, 0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0x56, 0xb2, 0xe3, 0xe2, 0x71, 0x85, 0x0a, 0xf9,
	0x64, 0xe6, 0xa5, 0x0a, 0x49, 0x71, 0x71, 0xe4, 0x27, 0x65, 0xa5, 0x26, 0x97, 0x64, 0xa6, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9,
	0x12, 0x4c, 0x60, 0x71, 0x30, 0x3b, 0x89, 0x0d, 0x6c, 0xae, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xd3, 0x94, 0xf3, 0xba, 0x66, 0x00, 0x00, 0x00,
}
