// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stop_visits.proto

package external_models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExternalStopVisit struct {
	Objectid             string                   `protobuf:"bytes,1,opt,name=objectid,proto3" json:"objectid,omitempty"`
	StopAreaRef          string                   `protobuf:"bytes,2,opt,name=stopAreaRef,proto3" json:"stopAreaRef,omitempty"`
	PassageOrder         string                   `protobuf:"bytes,3,opt,name=passageOrder,proto3" json:"passageOrder,omitempty"`
	VehicleJourneyRef    string                   `protobuf:"bytes,4,opt,name=vehicleJourneyRef,proto3" json:"vehicleJourneyRef,omitempty"`
	Monitored            bool                     `protobuf:"varint,5,opt,name=monitored,proto3" json:"monitored,omitempty"`
	ArrivalTimes         *ExternalStopVisit_Times `protobuf:"bytes,6,opt,name=arrival_times,json=arrivalTimes,proto3" json:"arrival_times,omitempty"`
	DepartureTimes       *ExternalStopVisit_Times `protobuf:"bytes,7,opt,name=departure_times,json=departureTimes,proto3" json:"departure_times,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ExternalStopVisit) Reset()         { *m = ExternalStopVisit{} }
func (m *ExternalStopVisit) String() string { return proto.CompactTextString(m) }
func (*ExternalStopVisit) ProtoMessage()    {}
func (*ExternalStopVisit) Descriptor() ([]byte, []int) {
	return fileDescriptor_17309d9b77d9e691, []int{0}
}

func (m *ExternalStopVisit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalStopVisit.Unmarshal(m, b)
}
func (m *ExternalStopVisit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalStopVisit.Marshal(b, m, deterministic)
}
func (m *ExternalStopVisit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalStopVisit.Merge(m, src)
}
func (m *ExternalStopVisit) XXX_Size() int {
	return xxx_messageInfo_ExternalStopVisit.Size(m)
}
func (m *ExternalStopVisit) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalStopVisit.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalStopVisit proto.InternalMessageInfo

func (m *ExternalStopVisit) GetObjectid() string {
	if m != nil {
		return m.Objectid
	}
	return ""
}

func (m *ExternalStopVisit) GetStopAreaRef() string {
	if m != nil {
		return m.StopAreaRef
	}
	return ""
}

func (m *ExternalStopVisit) GetPassageOrder() string {
	if m != nil {
		return m.PassageOrder
	}
	return ""
}

func (m *ExternalStopVisit) GetVehicleJourneyRef() string {
	if m != nil {
		return m.VehicleJourneyRef
	}
	return ""
}

func (m *ExternalStopVisit) GetMonitored() bool {
	if m != nil {
		return m.Monitored
	}
	return false
}

func (m *ExternalStopVisit) GetArrivalTimes() *ExternalStopVisit_Times {
	if m != nil {
		return m.ArrivalTimes
	}
	return nil
}

func (m *ExternalStopVisit) GetDepartureTimes() *ExternalStopVisit_Times {
	if m != nil {
		return m.DepartureTimes
	}
	return nil
}

type ExternalStopVisit_Times struct {
	Aimed                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=aimed,proto3" json:"aimed,omitempty"`
	Expected             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expected,proto3" json:"expected,omitempty"`
	Actual               *timestamp.Timestamp `protobuf:"bytes,3,opt,name=actual,proto3" json:"actual,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExternalStopVisit_Times) Reset()         { *m = ExternalStopVisit_Times{} }
func (m *ExternalStopVisit_Times) String() string { return proto.CompactTextString(m) }
func (*ExternalStopVisit_Times) ProtoMessage()    {}
func (*ExternalStopVisit_Times) Descriptor() ([]byte, []int) {
	return fileDescriptor_17309d9b77d9e691, []int{0, 0}
}

func (m *ExternalStopVisit_Times) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalStopVisit_Times.Unmarshal(m, b)
}
func (m *ExternalStopVisit_Times) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalStopVisit_Times.Marshal(b, m, deterministic)
}
func (m *ExternalStopVisit_Times) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalStopVisit_Times.Merge(m, src)
}
func (m *ExternalStopVisit_Times) XXX_Size() int {
	return xxx_messageInfo_ExternalStopVisit_Times.Size(m)
}
func (m *ExternalStopVisit_Times) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalStopVisit_Times.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalStopVisit_Times proto.InternalMessageInfo

func (m *ExternalStopVisit_Times) GetAimed() *timestamp.Timestamp {
	if m != nil {
		return m.Aimed
	}
	return nil
}

func (m *ExternalStopVisit_Times) GetExpected() *timestamp.Timestamp {
	if m != nil {
		return m.Expected
	}
	return nil
}

func (m *ExternalStopVisit_Times) GetActual() *timestamp.Timestamp {
	if m != nil {
		return m.Actual
	}
	return nil
}

type ExternalStopVisits struct {
	StopVisits           []*ExternalStopVisit `protobuf:"bytes,1,rep,name=stop_visits,json=stopVisits,proto3" json:"stop_visits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExternalStopVisits) Reset()         { *m = ExternalStopVisits{} }
func (m *ExternalStopVisits) String() string { return proto.CompactTextString(m) }
func (*ExternalStopVisits) ProtoMessage()    {}
func (*ExternalStopVisits) Descriptor() ([]byte, []int) {
	return fileDescriptor_17309d9b77d9e691, []int{1}
}

func (m *ExternalStopVisits) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalStopVisits.Unmarshal(m, b)
}
func (m *ExternalStopVisits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalStopVisits.Marshal(b, m, deterministic)
}
func (m *ExternalStopVisits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalStopVisits.Merge(m, src)
}
func (m *ExternalStopVisits) XXX_Size() int {
	return xxx_messageInfo_ExternalStopVisits.Size(m)
}
func (m *ExternalStopVisits) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalStopVisits.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalStopVisits proto.InternalMessageInfo

func (m *ExternalStopVisits) GetStopVisits() []*ExternalStopVisit {
	if m != nil {
		return m.StopVisits
	}
	return nil
}

func init() {
	proto.RegisterType((*ExternalStopVisit)(nil), "external_models.ExternalStopVisit")
	proto.RegisterType((*ExternalStopVisit_Times)(nil), "external_models.ExternalStopVisit.Times")
	proto.RegisterType((*ExternalStopVisits)(nil), "external_models.ExternalStopVisits")
}

func init() { proto.RegisterFile("stop_visits.proto", fileDescriptor_17309d9b77d9e691) }

var fileDescriptor_17309d9b77d9e691 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x89, 0xfd, 0x63, 0x3b, 0xa9, 0x96, 0xee, 0x29, 0x04, 0xc1, 0x90, 0x53, 0x0e, 0x92,
	0x4a, 0x04, 0xef, 0x22, 0x5e, 0x04, 0x11, 0xa3, 0x08, 0x9e, 0xca, 0x36, 0x99, 0xd6, 0x95, 0xa4,
	0xbb, 0xec, 0x6e, 0x4a, 0x7d, 0x06, 0x9f, 0xc3, 0xf7, 0x94, 0xec, 0xc6, 0xf8, 0xa7, 0x50, 0xf1,
	0x38, 0x33, 0xdf, 0xf7, 0x5b, 0xe6, 0x9b, 0x85, 0x89, 0xd2, 0x5c, 0xcc, 0xd6, 0x4c, 0x31, 0xad,
	0x62, 0x21, 0xb9, 0xe6, 0x64, 0x8c, 0x1b, 0x8d, 0x72, 0x45, 0x8b, 0x59, 0xc9, 0x73, 0x2c, 0x94,
	0x7f, 0xbc, 0xe4, 0x7c, 0x59, 0xe0, 0xd4, 0x8c, 0xe7, 0xd5, 0x62, 0xaa, 0x59, 0x89, 0x4a, 0xd3,
	0x52, 0x58, 0x47, 0xf8, 0xd6, 0x85, 0xc9, 0x55, 0x63, 0xba, 0xd7, 0x5c, 0x3c, 0xd6, 0x38, 0xe2,
	0xc3, 0x80, 0xcf, 0x5f, 0x30, 0xd3, 0x2c, 0xf7, 0x9c, 0xc0, 0x89, 0x86, 0x69, 0x5b, 0x93, 0x00,
	0xdc, 0xfa, 0xe1, 0x0b, 0x89, 0x34, 0xc5, 0x85, 0xb7, 0x67, 0xc6, 0xdf, 0x5b, 0x24, 0x84, 0x91,
	0xa0, 0x4a, 0xd1, 0x25, 0xde, 0xca, 0x1c, 0xa5, 0xd7, 0x31, 0x92, 0x1f, 0x3d, 0x72, 0x02, 0x93,
	0x35, 0x3e, 0xb3, 0xac, 0xc0, 0x6b, 0x5e, 0xc9, 0x15, 0xbe, 0xd6, 0xac, 0xae, 0x11, 0x6e, 0x0f,
	0xc8, 0x11, 0x0c, 0x4b, 0xbe, 0x62, 0x9a, 0x4b, 0xcc, 0xbd, 0x5e, 0xe0, 0x44, 0x83, 0xf4, 0xab,
	0x41, 0x6e, 0xe0, 0x80, 0x4a, 0xc9, 0xd6, 0xb4, 0x98, 0x99, 0xf5, 0xbc, 0x7e, 0xe0, 0x44, 0x6e,
	0x12, 0xc5, 0xbf, 0xd2, 0x88, 0xb7, 0x16, 0x8d, 0x1f, 0x6a, 0x7d, 0x3a, 0x6a, 0xec, 0xa6, 0x22,
	0x77, 0x30, 0xce, 0x51, 0x50, 0xa9, 0x2b, 0x89, 0x0d, 0x70, 0xff, 0x9f, 0xc0, 0xc3, 0x16, 0x60,
	0x6a, 0xff, 0xdd, 0x81, 0x9e, 0x85, 0x9f, 0x42, 0x8f, 0xb2, 0x12, 0x6d, 0xac, 0x6e, 0xe2, 0xc7,
	0xf6, 0x40, 0xf1, 0xe7, 0x81, 0x2c, 0xa0, 0x3e, 0x50, 0x6a, 0x85, 0xe4, 0x1c, 0x06, 0xb8, 0x11,
	0x98, 0x69, 0xcc, 0x4d, 0xd8, 0xbb, 0x4d, 0xad, 0x96, 0x24, 0xd0, 0xa7, 0x99, 0xae, 0x68, 0x61,
	0xf2, 0xdf, 0xed, 0x6a, 0x94, 0xe1, 0x13, 0x90, 0xad, 0x95, 0x14, 0xb9, 0xb4, 0x17, 0x6f, 0xbe,
	0x9a, 0xe7, 0x04, 0x9d, 0xc8, 0x4d, 0xc2, 0xbf, 0xc3, 0x48, 0x41, 0xb5, 0x90, 0x79, 0xdf, 0x3c,
	0x7b, 0xf6, 0x11, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xdd, 0x60, 0xb7, 0xb6, 0x02, 0x00, 0x00,
}
