// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vehicle_journeys.proto

package external_models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExternalVehicleJourney struct {
	Objectid             string   `protobuf:"bytes,1,opt,name=objectid,proto3" json:"objectid,omitempty"`
	LineRef              string   `protobuf:"bytes,2,opt,name=lineRef,proto3" json:"lineRef,omitempty"`
	OriginRef            string   `protobuf:"bytes,3,opt,name=originRef,proto3" json:"originRef,omitempty"`
	OriginName           string   `protobuf:"bytes,4,opt,name=originName,proto3" json:"originName,omitempty"`
	DestinationRef       string   `protobuf:"bytes,5,opt,name=destinationRef,proto3" json:"destinationRef,omitempty"`
	DestinationName      string   `protobuf:"bytes,6,opt,name=destinationName,proto3" json:"destinationName,omitempty"`
	Direction            string   `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"`
	ViaName              string   `protobuf:"bytes,8,opt,name=viaName,proto3" json:"viaName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalVehicleJourney) Reset()         { *m = ExternalVehicleJourney{} }
func (m *ExternalVehicleJourney) String() string { return proto.CompactTextString(m) }
func (*ExternalVehicleJourney) ProtoMessage()    {}
func (*ExternalVehicleJourney) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2317bc119de9bd2, []int{0}
}

func (m *ExternalVehicleJourney) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalVehicleJourney.Unmarshal(m, b)
}
func (m *ExternalVehicleJourney) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalVehicleJourney.Marshal(b, m, deterministic)
}
func (m *ExternalVehicleJourney) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalVehicleJourney.Merge(m, src)
}
func (m *ExternalVehicleJourney) XXX_Size() int {
	return xxx_messageInfo_ExternalVehicleJourney.Size(m)
}
func (m *ExternalVehicleJourney) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalVehicleJourney.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalVehicleJourney proto.InternalMessageInfo

func (m *ExternalVehicleJourney) GetObjectid() string {
	if m != nil {
		return m.Objectid
	}
	return ""
}

func (m *ExternalVehicleJourney) GetLineRef() string {
	if m != nil {
		return m.LineRef
	}
	return ""
}

func (m *ExternalVehicleJourney) GetOriginRef() string {
	if m != nil {
		return m.OriginRef
	}
	return ""
}

func (m *ExternalVehicleJourney) GetOriginName() string {
	if m != nil {
		return m.OriginName
	}
	return ""
}

func (m *ExternalVehicleJourney) GetDestinationRef() string {
	if m != nil {
		return m.DestinationRef
	}
	return ""
}

func (m *ExternalVehicleJourney) GetDestinationName() string {
	if m != nil {
		return m.DestinationName
	}
	return ""
}

func (m *ExternalVehicleJourney) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *ExternalVehicleJourney) GetViaName() string {
	if m != nil {
		return m.ViaName
	}
	return ""
}

type ExternalVehicleJourneys struct {
	VehicleJourneys      []*ExternalVehicleJourney `protobuf:"bytes,1,rep,name=vehicle_journeys,json=vehicleJourneys,proto3" json:"vehicle_journeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ExternalVehicleJourneys) Reset()         { *m = ExternalVehicleJourneys{} }
func (m *ExternalVehicleJourneys) String() string { return proto.CompactTextString(m) }
func (*ExternalVehicleJourneys) ProtoMessage()    {}
func (*ExternalVehicleJourneys) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2317bc119de9bd2, []int{1}
}

func (m *ExternalVehicleJourneys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalVehicleJourneys.Unmarshal(m, b)
}
func (m *ExternalVehicleJourneys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalVehicleJourneys.Marshal(b, m, deterministic)
}
func (m *ExternalVehicleJourneys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalVehicleJourneys.Merge(m, src)
}
func (m *ExternalVehicleJourneys) XXX_Size() int {
	return xxx_messageInfo_ExternalVehicleJourneys.Size(m)
}
func (m *ExternalVehicleJourneys) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalVehicleJourneys.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalVehicleJourneys proto.InternalMessageInfo

func (m *ExternalVehicleJourneys) GetVehicleJourneys() []*ExternalVehicleJourney {
	if m != nil {
		return m.VehicleJourneys
	}
	return nil
}

func init() {
	proto.RegisterType((*ExternalVehicleJourney)(nil), "external_models.ExternalVehicleJourney")
	proto.RegisterType((*ExternalVehicleJourneys)(nil), "external_models.ExternalVehicleJourneys")
}

func init() { proto.RegisterFile("vehicle_journeys.proto", fileDescriptor_f2317bc119de9bd2) }

var fileDescriptor_f2317bc119de9bd2 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4f, 0xc3, 0x40,
	0x0c, 0xc5, 0x95, 0x16, 0xfa, 0xc7, 0x48, 0x04, 0x79, 0x28, 0x27, 0x84, 0x50, 0xd5, 0x01, 0x32,
	0x65, 0x80, 0xcf, 0xc0, 0xc2, 0xc0, 0x90, 0x81, 0xb5, 0x4a, 0x1b, 0x03, 0xae, 0x92, 0x33, 0xba,
	0x1c, 0x11, 0x7c, 0x11, 0x3e, 0x2f, 0x8a, 0xaf, 0x94, 0xf6, 0xd4, 0xf1, 0xfd, 0xde, 0xf9, 0xc9,
	0x7e, 0x07, 0xb3, 0x8e, 0xde, 0x79, 0x5d, 0xd3, 0x72, 0x23, 0x9f, 0xce, 0xd2, 0x77, 0x9b, 0x7f,
	0x38, 0xf1, 0x82, 0x29, 0x7d, 0x79, 0x72, 0xb6, 0xac, 0x97, 0x8d, 0x54, 0x54, 0xb7, 0x8b, 0x9f,
	0x01, 0xcc, 0x1e, 0xb7, 0xec, 0x25, 0xcc, 0x3c, 0x85, 0x11, 0xbc, 0x82, 0x89, 0xac, 0x36, 0xb4,
	0xf6, 0x5c, 0x99, 0x64, 0x9e, 0x64, 0xd3, 0x62, 0xa7, 0xd1, 0xc0, 0xb8, 0x66, 0x4b, 0x05, 0xbd,
	0x9a, 0x81, 0x5a, 0x7f, 0x12, 0xaf, 0x61, 0x2a, 0x8e, 0xdf, 0xd8, 0xf6, 0xde, 0x50, 0xbd, 0x7f,
	0x80, 0x37, 0x00, 0x41, 0x3c, 0x97, 0x0d, 0x99, 0x13, 0xb5, 0xf7, 0x08, 0xde, 0xc2, 0x79, 0x45,
	0xad, 0x67, 0x5b, 0x7a, 0x16, 0x8d, 0x38, 0xd5, 0x37, 0x11, 0xc5, 0x0c, 0xd2, 0x3d, 0xa2, 0x61,
	0x23, 0x7d, 0x18, 0xe3, 0x7e, 0x9f, 0x8a, 0x5d, 0xbf, 0xb5, 0x58, 0x33, 0x0e, 0xfb, 0xec, 0x40,
	0x7f, 0x47, 0xc7, 0xa5, 0xce, 0x4f, 0xc2, 0x1d, 0x5b, 0xb9, 0x68, 0xe0, 0xf2, 0x78, 0x2f, 0x2d,
	0x16, 0x70, 0x11, 0xd7, 0x6b, 0x92, 0xf9, 0x30, 0x3b, 0xbb, 0xbf, 0xcb, 0xa3, 0x7e, 0xf3, 0xe3,
	0x19, 0x45, 0xda, 0x1d, 0x66, 0xae, 0x46, 0xfa, 0x3f, 0x0f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x29, 0x24, 0xb4, 0x5c, 0xb9, 0x01, 0x00, 0x00,
}
